# Generated by Django 5.1.1 on 2024-10-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employ_info',
            old_name='emp_desg',
            new_name='emp_desig',
        ),
    ]
