# Generated by Django 5.1.1 on 2024-10-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_emp_desg_employ_info_emp_desig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Djemployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Employ_info',
        ),
    ]
