# Generated by Django 5.1.1 on 2024-10-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_djemployee_delete_employ_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djemployee',
            old_name='emp_designation',
            new_name='emp_desig',
        ),
    ]
